
SELECT
    SALES_DATE,
    SUM(NET_AMOUNT) AS TOTAL_REVENUE,
    SUM(QTY) AS TOTAL_QTY,
    COUNT(DISTINCT SOURCE_DOC_ID) AS TOTAL_ORDERS
FROM CORE.FACT_SALES
WHERE IS_CANCELLED = FALSE
GROUP BY SALES_DATE
ORDER BY SALES_DATE;