SELECT *
FROM (
    SELECT
        TO_CHAR(DATE_TRUNC('MONTH', SALES_DATE), 'YYYY-MON') AS SALES_MONTH,
        PRODUCT_ID,
        PRODUCT_NAME,
        SUM(NET_AMOUNT) AS TOTAL_REVENUE,
        RANK() OVER (
            PARTITION BY DATE_TRUNC('MONTH', SALES_DATE)
            ORDER BY SUM(NET_AMOUNT) DESC
        ) AS RNK
    FROM CORE.FACT_SALES
    WHERE IS_CANCELLED = FALSE
      AND PRODUCT_NAME <> 'UNKNOWN'
    GROUP BY DATE_TRUNC('MONTH', SALES_DATE), PRODUCT_ID, PRODUCT_NAME
)
WHERE RNK <= 2;