CREATE OR REPLACE FILE FORMAT csv_format
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null')
EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE FILE FORMAT json_format
TYPE = JSON
STRIP_OUTER_ARRAY = TRUE
IGNORE_UTF8_ERRORS = TRUE;

show file formats;

CREATE OR REPLACE STAGE csv_stage
FILE_FORMAT = csv_format
COMMENT = 'Stage for CSV files (POS and Customers)';

CREATE OR REPLACE STAGE json_stage
FILE_FORMAT = json_format
COMMENT = 'Stage for Online Sales JSON file';


CREATE OR REPLACE TABLE RAW.STORE_SALES (
TRANSACTION_ID NUMBER(38,0),
TRANSACTION_TS TIMESTAMP_NTZ(9),
STORE_ID NUMBER(38,0),
PRODUCT_ID NUMBER(38,0),
QUANTITY NUMBER(38,0),
UNIT_PRICE NUMBER(12,2),
DISCOUNT_PCT NUMBER(6,2),
NET_AMOUNT NUMBER(14,2),
PAYMENT_METHOD VARCHAR
);


CREATE OR REPLACE TABLE RAW.CUSTOMERS (
CUSTOMER_ID NUMBER(38,0),
FIRST_NAME VARCHAR,
LAST_NAME VARCHAR,
GENDER VARCHAR,
AGE NUMBER(38,0),
REGION VARCHAR
);

COPY INTO RAW.STORE_SALES
FROM @csv_stage/POS/store_sale_csv.csv;

COPY INTO RAW.CUSTOMERS
FROM @csv_stage/CUSTOMER/customer_csv.csv;

select * from store_sales limit 50;

CREATE OR REPLACE TABLE RAW.ONLINE_SALES_RAW (
    SRC VARIANT
);

LIST @JSON_STAGE;
LIST @csv_STAGE;

COPY INTO RAW.ONLINE_SALES_RAW
FROM @JSON_STAGE/ONLINE
FILE_FORMAT = (FORMAT_NAME = json_format);

SELECT COUNT(*) FROM RAW.ONLINE_SALES_RAW;
SELECT * FROM RAW.ONLINE_SALES_RAW limit 50;


SELECT SRC FROM RAW.ONLINE_SALES_RAW;

