CREATE OR REPLACE TABLE CORE.ONLINE_ORDERS AS
SELECT
    SRC:order_id::NUMBER AS ORDER_ID,
    SRC:order_ts::TIMESTAMP_NTZ AS ORDER_TS,
    SRC:customer.customer_id::NUMBER AS CUSTOMER_ID,
    SRC:customer.region::VARCHAR AS CUSTOMER_REGION,
    SRC:device::VARCHAR AS DEVICE,
    SRC:status::VARCHAR AS STATUS
FROM RAW.ONLINE_SALES_RAW;

CREATE OR REPLACE TABLE CORE.ONLINE_ORDER_ITEMS AS
SELECT
    SRC:order_id::NUMBER AS ORDER_ID,
    item.value:line_no::NUMBER AS LINE_NO,
    item.value:product_id::NUMBER AS PRODUCT_ID,
    item.value:product_name::VARCHAR AS PRODUCT_NAME,
    item.value:category::VARCHAR AS CATEGORY,
    item.value:unit_price::NUMBER(12,2) AS UNIT_PRICE,
    item.value:qty::NUMBER(12,2) AS QTY
FROM RAW.ONLINE_SALES_RAW,
LATERAL FLATTEN(input => SRC:line_items) item;

SELECT COUNT(*) FROM CORE.ONLINE_ORDERS;
SELECT COUNT(*) FROM CORE.ONLINE_ORDER_ITEMS;

SELECT * FROM CORE.ONLINE_ORDERS;
SELECT * FROM CORE.ONLINE_ORDER_ITEMS;
